"""empty message

Revision ID: 0f6cc252e687
Revises: d5f2363fd514
Create Date: 2023-01-17 14:40:17.950999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6cc252e687'
down_revision = 'd5f2363fd514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistitems_id_category', sa.Integer(), nullable=False))
        batch_op.drop_constraint('category_playlistitems_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'play_list_items', ['playlistitems_id_category'], ['id'])
        batch_op.drop_column('playlistitems_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistitems_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('category_playlistitems_id_fkey', 'play_list_items', ['playlistitems_id'], ['id'])
        batch_op.drop_column('playlistitems_id_category')

    # ### end Alembic commands ###
