"""empty message

Revision ID: 18e91ce30860
Revises: 971f42125e70
Create Date: 2023-01-16 18:37:23.864829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e91ce30860'
down_revision = '971f42125e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnails', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('play_list_items_playlistdescription_key', type_='unique')
        batch_op.drop_constraint('play_list_items_playlistposition_key', type_='unique')
        batch_op.create_unique_constraint(None, ['thumbnails'])
        batch_op.drop_column('playlistdescription')
        batch_op.drop_column('playlistposition')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint('video_videoplayer_key', type_='unique')
        batch_op.drop_column('videoplayer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videoplayer', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('video_videoplayer_key', ['videoplayer'])

    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistposition', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('playlistdescription', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('play_list_items_playlistposition_key', ['playlistposition'])
        batch_op.create_unique_constraint('play_list_items_playlistdescription_key', ['playlistdescription'])
        batch_op.drop_column('thumbnails')

    # ### end Alembic commands ###
