"""empty message

Revision ID: 1c9c3e8e0515
Revises: bb1272e5394c
Create Date: 2023-01-17 18:00:28.026407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9c3e8e0515'
down_revision = 'bb1272e5394c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_playlistitems_id_category_fkey', type_='foreignkey')
        batch_op.drop_column('playlistitems_id_category')

    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistitems_id_category', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('category_playlistitems_id_category_fkey', 'play_list_items', ['playlistitems_id_category'], ['id'])

    # ### end Alembic commands ###
