"""empty message

Revision ID: 1e030970a043
Revises: 02bae895345c
Create Date: 2022-12-16 19:32:00.382115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e030970a043'
down_revision = '02bae895345c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coment', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coment')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coments')
    op.drop_table('likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='likes_user_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='likes_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    op.create_table('coments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coment', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='coments_user_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='coments_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='coments_pkey'),
    sa.UniqueConstraint('coment', name='coments_coment_key')
    )
    op.drop_table('like')
    op.drop_table('coment')
    # ### end Alembic commands ###
