"""empty message

Revision ID: 284c66029c00
Revises: f1a5f2af8ee8
Create Date: 2023-01-14 17:19:20.226668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284c66029c00'
down_revision = 'f1a5f2af8ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.drop_constraint('play_list_items_playlistdescription_key', type_='unique')
        batch_op.drop_column('playlistdescription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistdescription', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('play_list_items_playlistdescription_key', ['playlistdescription'])

    # ### end Alembic commands ###
