"""empty message

Revision ID: 71e851cd4fc0
Revises: 971f42125e70
Create Date: 2023-01-13 20:28:37.050646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e851cd4fc0'
down_revision = '971f42125e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_category_youtube_id_key', type_='unique')
        batch_op.drop_column('category_youtube_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_youtube_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('category_category_youtube_id_key', ['category_youtube_id'])

    # ### end Alembic commands ###
