"""empty message

Revision ID: 986b1ff58a15
Revises: 71e851cd4fc0
Create Date: 2023-01-13 20:38:40.236065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986b1ff58a15'
down_revision = '71e851cd4fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catefory_id', sa.Integer(), nullable=False))
        batch_op.alter_column('playlistdescription',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('playlistposition',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'category', ['catefory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('playlistposition',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('playlistdescription',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('catefory_id')

    # ### end Alembic commands ###
