"""empty message

Revision ID: a56843cf4a57
Revises: 946ad398f1a1
Create Date: 2023-01-17 14:34:50.803676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56843cf4a57'
down_revision = '946ad398f1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistitems_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('category_category_youtube_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'play_list_items', ['playlistitems_id'], ['id'])
        batch_op.drop_column('category_youtube_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_youtube_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('category_category_youtube_id_key', ['category_youtube_id'])
        batch_op.drop_column('playlistitems_id')

    # ### end Alembic commands ###
