"""empty message

Revision ID: bd123ce243a2
Revises: 1e030970a043
Create Date: 2022-12-16 20:43:32.170780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd123ce243a2'
down_revision = '1e030970a043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_youtube_id', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'category', ['category_youtube_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'category_youtube_id')
    # ### end Alembic commands ###
