"""empty message

Revision ID: cadf6a8130b2
Revises: 
Create Date: 2023-02-06 20:16:42.015162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadf6a8130b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelid', sa.String(length=120), nullable=False),
    sa.Column('channelbanner', sa.String(length=120), nullable=False),
    sa.Column('channeltitle', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelbanner'),
    sa.UniqueConstraint('channelid'),
    sa.UniqueConstraint('channeltitle')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=80), nullable=True),
    sa.Column('img', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('play_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlistid', sa.String(length=120), nullable=False),
    sa.Column('playlisttitle', sa.String(length=80), nullable=False),
    sa.Column('thumbnails', sa.String(length=120), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlistid'),
    sa.UniqueConstraint('playlisttitle'),
    sa.UniqueConstraint('thumbnails')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoid', sa.String(length=120), nullable=False),
    sa.Column('videotitle', sa.String(length=80), nullable=False),
    sa.Column('videodescription', sa.Text(), nullable=False),
    sa.Column('playlistitems_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['playlistitems_id'], ['play_list_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('videoid'),
    sa.UniqueConstraint('videotitle')
    )
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coment', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coment')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_later',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_later')
    op.drop_table('like')
    op.drop_table('coment')
    op.drop_table('video')
    op.drop_table('play_list_items')
    op.drop_table('user')
    op.drop_table('channel')
    op.drop_table('category')
    # ### end Alembic commands ###