"""empty message

Revision ID: cfe8b7679557
Revises: e71dba751f36
Create Date: 2023-01-15 18:33:36.405692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe8b7679557'
down_revision = 'e71dba751f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('play_list_items_catefory_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('catefory_id')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('video_catefory_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('catefory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catefory_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('video_catefory_id_fkey', 'category', ['catefory_id'], ['id'])
        batch_op.alter_column('channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('category_id')

    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catefory_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('play_list_items_catefory_id_fkey', 'category', ['catefory_id'], ['id'])
        batch_op.alter_column('channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
