"""empty message

Revision ID: e71dba751f36
Revises: 284c66029c00
Create Date: 2023-01-14 17:30:33.353768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71dba751f36'
down_revision = '284c66029c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistimg', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['playlistimg'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('playlistimg')

    # ### end Alembic commands ###
