"""empty message

Revision ID: f1a5f2af8ee8
Revises: 986b1ff58a15
Create Date: 2023-01-14 17:12:14.519523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a5f2af8ee8'
down_revision = '986b1ff58a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.drop_constraint('play_list_items_playlistposition_key', type_='unique')
        batch_op.drop_column('playlistposition')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('catefory_id', sa.Integer(), nullable=False))
        batch_op.alter_column('videodescription',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('videoplayer',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('playlistitems_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'channel', ['channel_id'], ['id'])
        batch_op.create_foreign_key(None, 'category', ['catefory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('playlistitems_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('videoplayer',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('videodescription',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('catefory_id')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('play_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlistposition', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('play_list_items_playlistposition_key', ['playlistposition'])

    # ### end Alembic commands ###
