"""empty message

Revision ID: fea155be7406
Revises: d05ba7564788
Create Date: 2023-01-13 18:39:27.835997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea155be7406'
down_revision = 'd05ba7564788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelid', sa.String(length=120), nullable=False),
    sa.Column('channelbanner', sa.String(length=120), nullable=False),
    sa.Column('channeltitle', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelbanner'),
    sa.UniqueConstraint('channelid'),
    sa.UniqueConstraint('channeltitle')
    )
    op.create_table('play_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlistid', sa.String(length=120), nullable=False),
    sa.Column('playlisttitle', sa.String(length=80), nullable=False),
    sa.Column('playlistdescription', sa.String(length=120), nullable=False),
    sa.Column('playlistposition', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlistdescription'),
    sa.UniqueConstraint('playlistid'),
    sa.UniqueConstraint('playlistposition'),
    sa.UniqueConstraint('playlisttitle')
    )
    op.add_column('video', sa.Column('videoid', sa.String(length=120), nullable=False))
    op.add_column('video', sa.Column('videotitle', sa.String(length=80), nullable=False))
    op.add_column('video', sa.Column('videodescription', sa.String(length=120), nullable=False))
    op.add_column('video', sa.Column('videoplayer', sa.String(length=120), nullable=False))
    op.drop_constraint('video_api_id_key', 'video', type_='unique')
    op.drop_constraint('video_title_key', 'video', type_='unique')
    op.drop_constraint('video_url_key', 'video', type_='unique')
    op.create_unique_constraint(None, 'video', ['videoid'])
    op.create_unique_constraint(None, 'video', ['videodescription'])
    op.create_unique_constraint(None, 'video', ['videotitle'])
    op.create_unique_constraint(None, 'video', ['videoplayer'])
    op.drop_constraint('video_category_id_fkey', 'video', type_='foreignkey')
    op.drop_column('video', 'category_id')
    op.drop_column('video', 'title')
    op.drop_column('video', 'url')
    op.drop_column('video', 'api_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('video_category_id_fkey', 'video', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'video', type_='unique')
    op.create_unique_constraint('video_url_key', 'video', ['url'])
    op.create_unique_constraint('video_title_key', 'video', ['title'])
    op.create_unique_constraint('video_api_id_key', 'video', ['api_id'])
    op.drop_column('video', 'videoplayer')
    op.drop_column('video', 'videodescription')
    op.drop_column('video', 'videotitle')
    op.drop_column('video', 'videoid')
    op.drop_table('play_list_items')
    op.drop_table('channel')
    # ### end Alembic commands ###
